### PR TITLE
fix (sipi): serveral bugs; Fragmentarium

### LINKED ISSUE #193: Downscaling of non-J2K-images
There is a trade-off between speed and quality of downscaling of images. Make this configurable

### LINKED ISSUE #197: Sipi crashes when serving IIIF url
http://localhost:1024/images/Bod_Ashm_463_a.jp2/full/32,/0/default.jpg
[Bod_Ashm_463_a.jp2.zip](https://github.com/dhlab-basel/Sipi/files/1141538/Bod_Ashm_463_a.jp2.zip)

### PR DESCRIPTION
**Pull request by lrosenth**
### Summary

This branch incorprates some critical bug fixes which make SIPI crash. Some of the bugs have been found using SIPI in the e-codices/fragmentarium environment

### Issues

- resolves #193
- resolves #197

### CODE REVIEW

**Comment by subotic** [comment]
resolves #197

**Comment by subotic** [comment]
resolves #193

**Comment by BiancoA** [comment]
Thanks for the request, I can review it tomorrow.

File: shttps/LuaServer.cpp [hunk 1]
```diff
@@ -2645,6 +2646,51 @@ namespace shttps {
     }
     //=========================================================================
 
+    const std::map<std::string,std::string> LuaServer::configStringTable(const std::string table, const std::string variable) {
```
Comment (benjamingeer) [inline shttps/LuaServer.cpp]: Could you add a comment explaining what this method does?

File: shttps/LuaServer.h [hunk 2]
```diff
@@ -162,6 +162,8 @@ namespace shttps {
```
Comment (benjamingeer) [inline shttps/LuaServer.h]: I think I can guess what these methods do, but it would be helpful to add Doxygen comments to make it clear.

**Comment by tobiasschweizer** [comment]
When running the Knora integration tests with this branch, Sipi crashes: 

```
iml-mortimer:Sipi_github tobi$ local/bin/sipi --config config/sipi.knora-config.lua 

Sipi Version 1.0 Beta (build 2017-07-18 15:29)
Sipi Source Git-Version: e844058
Jul 18 15:42:22  Sipi[53009] <Info>: Sipi Version 1.0 Beta (build 2017-07-18 15:29)
Jul 18 15:42:22  Sipi[53009] <Info>: Sipi Source Git-Version: e844058
Jul 18 15:42:22  Sipi[53009] <Info>: Cache at "./cache" cachesize=104857600 nfiles=0 hysteresis=0.100000
Jul 18 15:42:22  Sipi[53009] <Info>: Sipi server starting
Jul 18 15:42:22  Sipi[53009] <Info>: Serving images from ./images
Jul 18 15:42:22  Sipi[53009] <Info>: Starting shttps server with 16 threads
Jul 18 15:42:22  Sipi[53009] <Info>: Added route /make_thumbnail with script ./scripts/make_thumbnail.lua
Jul 18 15:42:22  Sipi[53009] <Info>: Added route /convert_from_binaries with script ./scripts/convert_from_binaries.lua
Jul 18 15:42:22  Sipi[53009] <Info>: Added route /convert_from_file with script ./scripts/convert_from_file.lua
Jul 18 15:42:22  Sipi[53009] <Info>: Added route /Knora_login with script ./scripts/Knora_login.lua
Jul 18 15:42:22  Sipi[53009] <Info>: Added route /Knora_logout with script ./scripts/Knora_logout.lua
Jul 18 15:42:22  Sipi[53009] <Info>: Server listening on port 1024
Jul 18 15:42:36  Sipi[53009] <Info>: Accepted connection from 127.0.0.1
Jul 18 15:43:23  Sipi[53009] <Info>: Accepted connection from 127.0.0.1
Segmentation fault: 11

```

File: src/SipiImage.cpp [hunk 3]
```diff
@@ -760,6 +763,109 @@ namespace Sipi {
...
+        for (size_t i = 0; i < nnx; i++) {
+            xlut[i] = (float) (i * (nx - 1)) / (float) (nnx - 1);
+        }
+        for (size_t j = 0; j < nny; j++) {
+            ylut[j] = (float) (j * (ny - 1)) / (float) (nny - 1);
+        }
+
+        if (bps == 8) {
+            byte *inbuf = pixels;
+            byte *outbuf = new byte[nnx * nny * nc];
```
Comment (BiancoA) [inline src/SipiImage.cpp]: Could we make those byte some kind of smart pointer? to avoid the `delete[] pixels;` line in the distructor

File: test/unit/sipiimage/sipiimage.cpp [hunk 4]
```diff
@@ -0,0 +1,47 @@
+#include "gtest/gtest.h"
+#include "gmock/gmock.h"
```
Comment (BiancoA) [inline test/unit/sipiimage/sipiimage.cpp]: @subotic Maybe we don't need gmock, what do you think?

File: src/SipiImage.cpp [hunk 5]
```diff
@@ -760,6 +763,109 @@ namespace Sipi {
...
+                        outbuf[nc * (y * nnx + x) + k] = inbuf[nc * (ylut[y] * nx + xlut[x]) + k];
+                    }
+                }
+            }
+            pixels = (byte *) outbuf;
+            delete[] inbuf;
+
+        } else {
+            return false;
+
```
Comment (retokromer) [inline src/SipiImage.cpp]: useless empty line

File: test/unit/sipiimage/sipiimage.cpp (hunk 4 above)
Comment (subotic) [inline test/unit/sipiimage/sipiimage.cpp]: No, it is not used at the moment.

File: src/formats/SipiIOJpeg.cpp [hunk 6]
```diff
@@ -667,28 +694,42 @@ namespace Sipi {
...
         //
-        if ((region != nullptr) && (region->getType()) != SipiRegion::FULL) {
+        if (!no_cropping) { // not no cropping (!!) means "do crop"!
+            //
+            // let's first crop the region (we read the full size image in this case)
+            //
             (void) img->crop(region);
+
+            //
+            // no we scale the region to the desired size
```
Comment (retokromer) [inline src/formats/SipiIOJpeg.cpp]: now we

**Comment by tobiasschweizer** [comment]
commit https://github.com/dhlab-basel/Sipi/pull/198/commits/af63c3215fffbb0b40a63a74c9889a3143de3555 resolves https://github.com/dhlab-basel/Sipi/pull/198#issuecomment-316086467

File: test/e2e/test_02_server.py [hunk 7]
```diff
@@ -77,36 +77,36 @@ def test_lausanne_thumbnail_alpha(self, manager):
...
 
     def test_concurrency(self, manager):
-        """handle many concurrent requests for different URLs"""
+        """handle many concurrent requests for different URLs (this may take a while, please be patient)"""
 
         # The command-line arguments we want to pass to ab for each process.
         
         filename = "load_test.jpx"
 
         ab_processes = [
```
Comment (tobiasschweizer) [inline test/e2e/test_02_server.py]: @lrosenth @benjamingeer The tests pass on my MacBook Air (2.2 GHz Intel Core i7, 8 GB 1600 MHz DDR3, macOs Sierra).

The load test's settings may have to be adapted for production conditions. Maybe we could define different scenarios. For now, it is important that bugs like the non thread safe XMP lib are detected.

Comment (tobiasschweizer) [inline test/e2e/test_02_server.py]: I haven't tried the current settings on `develop`. The load tests should make Sipi crash because of the no thread safe XMP lib.

**Comment by tobiasschweizer** [comment]
Some load tests got added and this branch seems fine now. I will merge it back to `develop` (which still has the concurrency bug).

**Comment by tobiasschweizer** [comment]
I will fix the  `libpng` problem first

File: config/sipi.config.lua [hunk 8]
```diff
@@ -49,6 +49,29 @@ sipi = {
...
 
     --
+    -- SIPI is using libjpeg to generate the JPEG images. libjpeg requires a quality value which
+    -- corresponds to the compression rate. 100 is (almost) no compression and best quality, 0
+    -- would be full compression and no quality. Reasonable values are between 30 and 95...
+    --
+    jpeg_quality = 60,
+
+    --
+    -- For scaling images, SIPI offers two methods. The value "high" offers best quality using expensive
```
Comment (retokromer) [inline config/sipi.config.lua]: Why not simply `SIPI offers two methods for scaling images.`?

File: config/sipi.config.lua [hunk 9]
```diff
@@ -49,6 +49,29 @@ sipi = {
...
+    -- algorithms (bilinear interpolation, if downscaling the image is first scaled up  to an integer
```
Comment (retokromer) [inline config/sipi.config.lua]: nit-picking: two spaces between `scaled up` and `to an integer`

File: config/sipi.config.lua (hunk 8 above)
Comment (tobiasschweizer) [inline config/sipi.config.lua]: Would you mind creating a branch to which you could apply your suggestions? I propose to create that branch from `develop` once `fragmentarium` is merged.

**Comment by tobiasschweizer** [comment]
@subotic the load tests fail. I think this is because `ab` is not installed on the OS. For Ubuntu `apache2-utils` is required: http://manpages.ubuntu.com/manpages/xenial/man1/ab.1.html

Could you add that?

**Comment by subotic** [comment]
yes, I can add them.

**Comment by tobiasschweizer** [comment]
Super cool, thx.

On 17 Aug 2017, at 17:23, Ivan Subotic <notifications@github.com<mailto:notifications@github.com>> wrote:


yes, I can add them.

File: shttps/LuaServer.h (hunk 2 above)
Comment (lrosenth) [inline shttps/LuaServer.h]: done!

**Comment by tobiasschweizer** [comment]
'ab' gets a timeout, I guess you are right. I suggest we merge it anyway. Maybe we should define several load tesr scenarios.

**Comment by tobiasschweizer** [comment]
Ok, increased the `ab` to 300 seconds, and now it passes
